language: node_js
sudo: false
node_js:
- "6"
cache:
  directories:
  - node_modules
env:
  global:
  - ENCRYPTION_LABEL: "1af81b20c5ba"
  - COMMIT_AUTHOR_EMAIL: "fand.gmork@gmail.com"
script:
- npm test
- bash deploy.sh
